language: node_js

os:
  - linux
  - osx
#  - windows
# windows doesn't work on travis
  
node_js:
    - "10"
    - "11"
    - "12"
    - "13"
    
    
install:
    - npm install
    - npm install --save vuepress
script:
    - npx npm run build
cache:
    directories:
        - "node_modules"
notifications:
    email: true

jobs:
  include:
    - stage: docs release
      node_js: "10"
      script: 
        - echo "Deploying to npm ..."
        - chmod 700 addAds.sh && ./addAds.sh
        - npm install
        - npm run docs:build
        - cp ads.txt docs/.vuepress/dist || true
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        repo: FriendlyUser/vuepress-theme-cool-starter
        keep-history: true
        target-branch: gh-pages
        on:
            branch: master
