language: node_js
node_js:
    - "10"
install:
    - npm install
script:
    - npm run docs:build
cache:
    directories:
        - "node_modules"
notifications:
    email: true
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: FriendlyUser/vuepress-theme-cool-starter
    keep-history: true
    target-branch: gh-pages
    on:
        branch: master